version: '2'
services:
  php:
    build: ./docker/php
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./app:/var/www/app/

  composer:
    restart: 'no'
    image: composer:latest
    command: install
    volumes:
      - ./app:/app
